import Link from "next/link";
import "./globals.css";
import { ToastContainer } from "react-toastify";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <nav className="p-4 bg-orange-500 flex gap-4 mb-4">
          <Link href="/">Home</Link>
          <Link href="/posts">Posts</Link>
          <Link href="/users">Users</Link>
          <Link href="/login">Login</Link>
          <Link href="/books">Books</Link>
          <Link href="/booklibrary">Library</Link>
          <Link href="/brianbook">Brian book</Link>

        </nav>
        {children}
        <ToastContainer />
      </body>
    </html>
  );
}
